// <auto-generated />
using System;
using Buteco.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Buteco.Api.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260807013022_AddAgentDelegationCatalog")]
    partial class AddAgentDelegationCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Buteco.Api.A2A.A2ATaskRecord", b =>
                {
                    b.Property<string>("TaskId")
                        .HasColumnType("text")
                        .HasColumnName("task_id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("ContextId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("context_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("StatusTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_timestamp");

                    b.HasKey("TaskId");

                    b.HasIndex("AgentId");

                    b.HasIndex("ContextId");

                    b.HasIndex("State");

                    b.ToTable("a2a_tasks", (string)null);
                });

            modelBuilder.Entity("Buteco.Api.AgentDelegations.Entities.AgentDelegation", b =>
                {
                    b.Property<Guid>("SourceAgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetAgentId")
                        .HasColumnType("uuid");

                    b.HasKey("SourceAgentId", "TargetAgentId");

                    b.HasIndex("TargetAgentId");

                    b.ToTable("agent_delegations", (string)null);
                });

            modelBuilder.Entity("Buteco.Api.AgentMcpBindings.Entities.AgentMcpServer", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("McpServerId")
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedTools")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_tools")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("AgentId", "McpServerId");

                    b.HasIndex("McpServerId");

                    b.ToTable("agent_mcp_servers", (string)null);
                });

            modelBuilder.Entity("Buteco.Api.Agents.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("skills")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("Buteco.Api.McpServers.Entities.McpServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedCredential")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("mcp_servers", (string)null);
                });

            modelBuilder.Entity("Buteco.Api.A2A.A2ATaskRecord", b =>
                {
                    b.HasOne("Buteco.Api.Agents.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Buteco.Api.AgentDelegations.Entities.AgentDelegation", b =>
                {
                    b.HasOne("Buteco.Api.Agents.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("SourceAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buteco.Api.Agents.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("TargetAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Buteco.Api.AgentMcpBindings.Entities.AgentMcpServer", b =>
                {
                    b.HasOne("Buteco.Api.Agents.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buteco.Api.McpServers.Entities.McpServer", null)
                        .WithMany()
                        .HasForeignKey("McpServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
