// <auto-generated />
using System;
using Buteco.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Buteco.Api.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Buteco.Api.A2A.A2ATaskRecord", b =>
                {
                    b.Property<string>("TaskId")
                        .HasColumnType("text")
                        .HasColumnName("task_id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("ContextId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("context_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("StatusTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_timestamp");

                    b.HasKey("TaskId");

                    b.HasIndex("AgentId");

                    b.HasIndex("ContextId");

                    b.HasIndex("State");

                    b.ToTable("a2a_tasks", (string)null);
                });

            modelBuilder.Entity("Buteco.Api.AgentDelegations.Entities.AgentDelegation", b =>
                {
                    b.Property<Guid>("SourceAgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetAgentId")
                        .HasColumnType("uuid");

                    b.HasKey("SourceAgentId", "TargetAgentId");

                    b.HasIndex("TargetAgentId");

                    b.ToTable("agent_delegations", (string)null);
                });

            modelBuilder.Entity("Buteco.Api.AgentKnowledgeBindings.Entities.AgentKnowledgeBase", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KnowledgeBaseId")
                        .HasColumnType("uuid");

                    b.HasKey("AgentId", "KnowledgeBaseId");

                    b.HasIndex("KnowledgeBaseId");

                    b.ToTable("agent_knowledge_bases", (string)null);
                });

            modelBuilder.Entity("Buteco.Api.AgentMcpBindings.Entities.AgentMcpServer", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("McpServerId")
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedTools")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_tools")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("AgentId", "McpServerId");

                    b.HasIndex("McpServerId");

                    b.ToTable("agent_mcp_servers", (string)null);
                });

            modelBuilder.Entity("Buteco.Api.Agents.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("skills")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("Buteco.Api.EmbeddingMetrics.Entities.EmbeddingCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Dimensions")
                        .HasColumnType("integer");

                    b.Property<double>("DurationMs")
                        .HasColumnType("double precision");

                    b.Property<bool>("Failed")
                        .HasColumnType("boolean");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("integer");

                    b.Property<int>("InputCount")
                        .HasColumnType("integer");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<Guid>("KnowledgeBaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("KnowledgeIndexingAttemptId")
                        .HasColumnType("uuid");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeIndexingAttemptId");

                    b.HasIndex("TaskId");

                    b.ToTable("embedding_calls", (string)null);
                });

            modelBuilder.Entity("Buteco.Api.EmbeddingMetrics.Entities.KnowledgeIndexingAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<int>("ContentRevision")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailurePhase")
                        .HasColumnType("text");

                    b.Property<int?>("FragmentCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("KnowledgeBaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KnowledgeDocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeDocumentId");

                    b.HasIndex("StartedAt");

                    b.ToTable("knowledge_indexing_attempts", (string)null);
                });

            modelBuilder.Entity("Buteco.Api.ExecutionMetrics.Entities.DelegationOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("DurationMs")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("LastObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastObservedTargetState")
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SourceAgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceTaskId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SuccessfulReadCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetAgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetTaskId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SourceAgentId");

                    b.HasIndex("SourceTaskId");

                    b.HasIndex("TargetAgentId");

                    b.ToTable("delegation_outcomes", (string)null);
                });

            modelBuilder.Entity("Buteco.Api.ExecutionMetrics.Entities.ProviderCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("CachedInputTokens")
                        .HasColumnType("bigint");

                    b.Property<double>("DurationMs")
                        .HasColumnType("double precision");

                    b.Property<bool>("Failed")
                        .HasColumnType("boolean");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("integer");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("provider_calls", (string)null);
                });

            modelBuilder.Entity("Buteco.Api.ExecutionMetrics.Entities.TaskExecution", b =>
                {
                    b.Property<string>("TaskId")
                        .HasColumnType("text");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContextId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DelegationDepth")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailurePhase")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LockAcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceAgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceTaskId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TerminalState")
                        .HasColumnType("text");

                    b.HasKey("TaskId");

                    b.HasIndex("AgentId");

                    b.HasIndex("StartedAt");

                    b.ToTable("task_executions", (string)null);
                });

            modelBuilder.Entity("Buteco.Api.KnowledgeBases.Entities.KnowledgeBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("knowledge_bases", (string)null);
                });

            modelBuilder.Entity("Buteco.Api.KnowledgeDocuments.Entities.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .HasColumnType("text");

                    b.Property<int>("ContentLengthBytes")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasComputedColumnSql("octet_length(\"ExtractedText\")", true);

                    b.Property<int>("ContentRevision")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtractedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<int>("FragmentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("IndexedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IndexingAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("IndexingStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("KnowledgeBaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeBaseId");

                    b.ToTable("knowledge_documents", (string)null);
                });

            modelBuilder.Entity("Buteco.Api.KnowledgeFragments.Entities.KnowledgeFragment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(4096)");

                    b.Property<int>("EmbeddingDimensions")
                        .HasColumnType("integer");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmbeddingProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("KnowledgeBaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KnowledgeDocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeBaseId");

                    b.HasIndex("KnowledgeDocumentId");

                    b.ToTable("knowledge_fragments", (string)null);
                });

            modelBuilder.Entity("Buteco.Api.McpServers.Entities.McpServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedCredential")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("mcp_servers", (string)null);
                });

            modelBuilder.Entity("Buteco.Api.A2A.A2ATaskRecord", b =>
                {
                    b.HasOne("Buteco.Api.Agents.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Buteco.Api.AgentDelegations.Entities.AgentDelegation", b =>
                {
                    b.HasOne("Buteco.Api.Agents.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("SourceAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buteco.Api.Agents.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("TargetAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Buteco.Api.AgentKnowledgeBindings.Entities.AgentKnowledgeBase", b =>
                {
                    b.HasOne("Buteco.Api.Agents.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buteco.Api.KnowledgeBases.Entities.KnowledgeBase", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Buteco.Api.AgentMcpBindings.Entities.AgentMcpServer", b =>
                {
                    b.HasOne("Buteco.Api.Agents.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buteco.Api.McpServers.Entities.McpServer", null)
                        .WithMany()
                        .HasForeignKey("McpServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Buteco.Api.EmbeddingMetrics.Entities.EmbeddingCall", b =>
                {
                    b.HasOne("Buteco.Api.EmbeddingMetrics.Entities.KnowledgeIndexingAttempt", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeIndexingAttemptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Buteco.Api.ExecutionMetrics.Entities.TaskExecution", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Buteco.Api.ExecutionMetrics.Entities.DelegationOutcome", b =>
                {
                    b.HasOne("Buteco.Api.ExecutionMetrics.Entities.TaskExecution", null)
                        .WithMany()
                        .HasForeignKey("SourceTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Buteco.Api.ExecutionMetrics.Entities.ProviderCall", b =>
                {
                    b.HasOne("Buteco.Api.ExecutionMetrics.Entities.TaskExecution", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Buteco.Api.KnowledgeDocuments.Entities.KnowledgeDocument", b =>
                {
                    b.HasOne("Buteco.Api.KnowledgeBases.Entities.KnowledgeBase", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Buteco.Api.KnowledgeFragments.Entities.KnowledgeFragment", b =>
                {
                    b.HasOne("Buteco.Api.KnowledgeDocuments.Entities.KnowledgeDocument", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
